### ISSUE TITLE
Rabbit MQ uuid is throwing an error

### ISSUE THREAD

**Issue by maganuk** [node-ts/bus#141]
Publishing a message to Rabbit MQ is throwing an error:

ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'v4')
TypeError: Cannot read properties of undefined (reading 'v4')
    at RabbitMqTransport.publishMessage (C:\test\node_modules\@node-ts\bus-rabbitmq\src\rabbitmq-transport.ts:253:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at RabbitMqTransport.publish (C:\test\node_modules\@node-ts\bus-rabbitmq\src\rabbitmq-transport.ts:73:5)

I'm currently using v8 of UUID, however even after downgrading to v3 the error persists.

**Comment by adenhertog** [comment]
hey @maganuk thanks for the feedback, the fix is available in `v1.0.1` of `@node-ts/bus-rabbitmq`
